name: Build and test

on: [push, pull_request]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

  test:
    name: Test with coverage
    needs: build
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v -coverprofile=.coverprofile ./...

      - name: Send coverage to coveralls.io
        uses: shogo82148/actions-goveralls@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          path-to-profile: .coverprofile
